### ISSUE TITLE
Vector Heading

### ISSUE THREAD

**Issue by edwardloveall** [unn4m3d/crystaledge#2]
Hello. I've been enjoying this library and I was wondering if you'd take a PR to add a `heading` method to Vector2. Something like:

```crystal
def heading
  atan(self.y / self.x)
end
```

Maybe this library is not really supposed to be about spacial vectors in which case I totally get not adding this, but I thought I'd check. 🙂

**Comment by unn4m3d** [comment]
Sorry for a long response time. I've updated the code, [that method](https://github.com/unn4m3d/crystaledge/blob/dec30bdfe4984b78342aa29e60938939a711d782/src/crystaledge/vector2.cr#L66) is now available in [version 0.2.1](https://github.com/unn4m3d/crystaledge/releases/tag/v0.2.1)

**Comment by edwardloveall** [comment]
Thanks so much @unn4m3d! No worries about the response time. 😄
